services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    container_name: "ob-server"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${SERVER_PORT}
      DYNAMODB_URI: ${DYNAMODB_URI}
      AWS_REGION: eu-south-2
      AWS_ACCESS_KEY_ID: xx
      AWS_SECRET_ACCESS_KEY: xx
    depends_on:
      - dynamodb-local
    env_file: .env

  client:
    build:
      context: ./client
    container_name: "ob-client"
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      PORT: ${CLIENT_PORT}
    env_file: .env

  dynamodb-local:
    image: amazon/dynamodb-local:2.5.3
    container_name: dynamodb
    ports:
      - "${DYNAMODB_PORT}:${DYNAMODB_PORT}"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    env_file: .env

volumes:
  dynamodb-data: