AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Offering Bowl DynamoDB tables.

Resources:
    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Users
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: role
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: role-index
                  KeySchema:
                      - AttributeName: role
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    SettingsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Settings
            AttributeDefinitions:
                - AttributeName: settingsId
                  AttributeType: S
                - AttributeName: userId
                  AttributeType: S
            KeySchema:
                - AttributeName: settingsId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: userId-index
                  KeySchema:
                      - AttributeName: userId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    ProfileTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Profile
            AttributeDefinitions:
                - AttributeName: profileId
                  AttributeType: S
                - AttributeName: userId
                  AttributeType: S
            KeySchema:
                - AttributeName: profileId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: userId-index
                  KeySchema:
                      - AttributeName: userId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    ActivitiesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Activities
            AttributeDefinitions:
                - AttributeName: activityId
                  AttributeType: S
                - AttributeName: userId
                  AttributeType: S
            KeySchema:
                - AttributeName: activityId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: userId-index
                  KeySchema:
                      - AttributeName: userId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    ContractsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Contracts
            AttributeDefinitions:
                - AttributeName: contractId
                  AttributeType: S
                - AttributeName: patronId
                  AttributeType: S
                - AttributeName: monasticId
                  AttributeType: S
            KeySchema:
                - AttributeName: contractId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: patronId-monasticId-index
                  KeySchema:
                      - AttributeName: patronId
                        KeyType: HASH
                      - AttributeName: monasticId
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    PostsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Posts
            AttributeDefinitions:
                - AttributeName: postId
                  AttributeType: S
                - AttributeName: monasticId
                  AttributeType: S
            KeySchema:
                - AttributeName: postId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: monasticId-index
                  KeySchema:
                      - AttributeName: monasticId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    ReceiptsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Receipts
            AttributeDefinitions:
                - AttributeName: receiptId
                  AttributeType: S
                - AttributeName: contractId
                  AttributeType: S
            KeySchema:
                - AttributeName: receiptId
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: contractId-index
                  KeySchema:
                      - AttributeName: contractId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            BillingMode: PAY_PER_REQUEST

    MediaTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Media
            AttributeDefinitions:
                - AttributeName: mediaId
                  AttributeType: S
            KeySchema:
                - AttributeName: mediaId
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
